### ISSUE TITLE
Encrypt/Decrypt Content

### ISSUE THREAD

**Issue by stefanwerfling** [tniessen/node-mceliece-nist#2]
Is this due to the strange names of the functions or is there no function for encrypting and decrypting a buffer with secret content? I have skimmed the code and see something with decryptKey, which suggests that the key is decrypted?

```
Napi::ObjectWrap<McEliece>::InstanceMethod("keypair", &McEliece::Keypair),
      Napi::ObjectWrap<McEliece>::InstanceMethod("generateKey", &McEliece::GenerateKey),
      Napi::ObjectWrap<McEliece>::InstanceMethod("decryptKey", &McEliece::DecryptKey),
      Napi::ObjectWrap<McEliece>::InstanceAccessor("keySize", &McEliece::GetKeySize, nullptr),
      Napi::ObjectWrap<McEliece>::InstanceAccessor("encryptedKeySize", &McEliece::GetEncryptedKeySize, nullptr),
      Napi::ObjectWrap<McEliece>::InstanceAccessor("publicKeySize", &McEliece::GetPublicKeySize, nullptr),
      Napi::ObjectWrap<McEliece>::InstanceAccessor("privateKeySize", &McEliece::GetPrivateKeySize, nullptr)
```

Normally you load/generate a key pair (private/public key). Then you encrypt something with the public key and the person who receives the message decrypts it with the private key.

I would have expected functions like this:
* loadKeyPair
* saveKeyPair
* genKeyPair
* encrypt
* decrypt

Maybe you can clarify this or provide a more precise example with "Hello World" as the secret message.

```typescript
const content = 'Hello World';
.... ?
```

**Comment by tniessen** [comment]
@stefanwerfling Thank you for opening an issue!

> Normally you load/generate a key pair (private/public key). Then you encrypt something with the public key and the person who receives the message decrypts it with the private key.

That is true for traditional public-key encryption algorithms (such as, for example, RSA). McEliece, at least in the form submitted to NIST for standardization, is _not_ a public-key encryption algorithm but it is a key encapsulation mechanism (KEM). You can find more information on KEMs and on how they differ from public-key encryption [on Wikipedia](https://en.wikipedia.org/wiki/Key_encapsulation_mechanism).

That same Wikipedia page lists three algorithms:

- *Key generation* is implemented by `keypair()`.
- *Encapsulation* is implemented by `generateKey()`.
- *Decapsulation* is implemented by `decryptKey()`.

Please do let me know if my explanation is unclear, and I'd be happy to elaborate.

On a side note, traditional public-key encryption appears to be increasingly unpopular. RSA encryption is largely being replaced by ECDH/X25519, which only facilitate key exchange and leave encryption up to symmetric ciphers. Similarly, with a KEM, both parties obtain a secret key and can then use that secret key with a symmetric cipher in order to encrypt/decrypt messages. The KEM itself does not encrypt any application data.

This is generally considered a more future-proof design than traditional public-key encryption. In fact, for the ongoing standardization effort of post-quantum cryptographic algorithms, NIST is only considering two kinds of algorithms: KEMs and digital signature algorithms.

If you'd like to experiment with other post-quantum KEMs, please consider using https://github.com/tniessen/node-pqclean. It is significantly larger than this package but supports a wide range of algorithms and has a much more modern API. (I maintain both and the McEliece implementations are compatible.)

**Comment by stefanwerfling** [comment]
Hello @tniessen that was very helpful, I wasn't still up to date, I know mceliece from a time when it was used like RSA (in Java).  Of course I want to stick to the latest standards, so I'm going to research the key encapsulation mechanism (KEM) now. 

Thank you very much for the quick reply.

Maybe an example where the content is shown and then encrypted/signed will still help.

**Comment by tniessen** [comment]
I'll start with the example from the `README.md` but I'll add some comments:

```js
const { McEliece } = require('mceliece-nist');

const kem = new McEliece('mceliece8192128');
// Alice's key pair. She only shared the public key with Bob.
const { publicKey, privateKey } = kem.keypair();

// Bob uses Alice's public key to generate both the shared secret key and
// the ciphertext that Alice can later use to obtain the same secret key.
// He only shares encryptedKey with Alice.
const { key, encryptedKey } = kem.generateKey(publicKey);
console.log(`Bob is using the key ${key.toString('hex')}`);

// Alice uses the encryptedKey (i.e., ciphertext) and her own private key
// to obtain the same shared secret key, i.e., Bob's variable key is now
// equal to Alice's variable receivedKey.
const receivedKey = kem.decryptKey(privateKey, encryptedKey);
console.log(`Alice is using the key ${receivedKey.toString('hex')}`);
```

Both parties can now use the same secret key: Bob generated the key (variable `key`) and sent the `encryptedKey` to Alice (using Alice's public key). Alice decapsulated the secret key (variable `receivedKey`) using her `privateKey`. The variable `key` is local to Bob and the variables `privateKey` and `receivedKey` are local to Alice.

> [!Note]
> This setup is very similar to ECDH (or X25519/X448) with one-sided ephemeral keys. Instead of encapsulation, Bob would use ECDH to derive a shared secret from his own (ephemeral) private key and Alice's public key, and would then share his public key with Alice, which allows her to securely derive the same shared secret.

Without Alice's `privateKey`, it is infeasible for anyone to obtain `key` from `encryptedKey`. Thus, this mechanism achieves a secure key exchange (similar to Diffie-Hellman/ECDH, but with additional post-quantum security).

Regardless of whether you use a KEM, such as McEliece, or Diffie-Hellman/ECDH/X25519, you now have shared some secret key securely.

> [!Note]
> With Diffie-Hellman/ECDH/X25519, the shared secret should be post-processed before being used as a key (see, for example, [libsodium's implementation](https://doc.libsodium.org/key_exchange#algorithm-details)). With the McEliece KEM, such post-processing is typically not necessary.

Bob can now use `key` to encrypt the actual message, e.g., using AES-GCM. Because we used `mceliece8192128`, the shared secret has 32 bytes, i.e., 256 bits, which is great for a (very strong) instance of AES-GCM:

```js
const { createCipheriv, randomBytes } = require('node:crypto');

const message = 'Hello world';
const iv = randomBytes(12);
const cipher = createCipheriv('aes-256-gcm', key, iv);
const ciphertext = Buffer.concat([cipher.update(message), cipher.final()]);
const authTag = cipher.getAuthTag();
```

> [!Note]
> The `authTag` is a feature of AES-GCM, which supports [Authenticated Encryption](https://en.wikipedia.org/wiki/Authenticated_encryption). Other modes of operation, such as AES-CTR, do not use authentication tags.

Bob could have done all this without communicating with Alice, aside from obtaining her `publicKey` somehow. For Alice to be able to decrypt the `ciphertext`, Bob needs to send to her:

- `encryptedKey`
- `iv`
- `ciphertext`
- `authTag`

None of these fields are secret -- they are useless without Alice's `privateKey`.

Alice obtains the `receivedKey` from the `encryptedKey` and her `privateKey` and can then decrypt the ciphertext:

```js
const { createDecipheriv } = require('node:crypto');

const decipher = createDecipheriv('aes-256-gcm', receivedKey, iv);
decipher.setAuthTag(authTag);
const receivedMessage = Buffer.concat([decipher.update(ciphertext), decipher.final()])
console.log(receivedMessage.toString());
```

These three code snippets should work just fine if executed in this order (and in the same scope).

Please let me know if you have any questions!

**Comment by stefanwerfling** [comment]
@tniessen That was very detailed, thank you very much!

**Comment by tniessen** [comment]
No problem at all, please feel free to open another issue in case of any questions! :)
